version: '3'

services:
  web:
    build: .
    command: bash -c "python3 -m uvicorn rental_app.asgi:application --host 0.0.0.0"
    container_name: rental_app
    volumes:
      - .:/rental_app
    ports:
      - "80:8000"